### ISSUE TITLE
TA-FireEye_Helix  for Splunk integration is not working

### ISSUE THREAD

**Issue by sujamaskey9099** [pentestfail/TA-FireEye_Helix#1]
We recently upgrade Splunk Enterprise version to 8.2. I reached out to Splunk support and provided Splunk diag file to Splunk support. Splunk support identified errors about the 'sendemail' alert action failing ( see below for exact log message). What those messages above indicates is a conflict with the lib 'urllib2', as of Splunk 8.0.0 , Splunk transitioned to Python3. In Python 3+ , urllib2 is replaced with urllib.request. 

Splunk recommendation is to engage the FireEye Team to update their scripts in this app, or import urllib.request as urllib2.

Please can you help.

Thanks
Suja 

errors about the 'sendemail' alert action failing.

08-23-2021 16:59:12.015 +0000 ERROR sendmodalert [19189 AlertNotifierWorker-0] - action=send_notable_event_to_fireeye_helix STDERR - Traceback (most recent call last):
08-23-2021 16:59:12.015 +0000 ERROR sendmodalert [19189 AlertNotifierWorker-0] - action=send_notable_event_to_fireeye_helix STDERR - File "/opt/splunk/etc/apps/TA-fireeye-helix-api-integration/bin/send_notable_event_to_fireeye_helix.py", line 9, in <module>
08-23-2021 16:59:12.015 +0000 ERROR sendmodalert [19189 AlertNotifierWorker-0] - action=send_notable_event_to_fireeye_helix STDERR - from alert_actions_base import ModularAlertBase
08-23-2021 16:59:12.015 +0000 ERROR sendmodalert [19189 AlertNotifierWorker-0] - action=send_notable_event_to_fireeye_helix STDERR - File "/opt/splunk/etc/apps/TA-fireeye-helix-api-integration/bin/ta_fireeye_helix_api_integration/alert_actions_base.py", line 14, in <module>
08-23-2021 16:59:12.015 +0000 ERROR sendmodalert [19189 AlertNotifierWorker-0] - action=send_notable_event_to_fireeye_helix STDERR - from logging_helper import get_logger
08-23-2021 16:59:12.016 +0000 ERROR sendmodalert [19189 AlertNotifierWorker-0] - action=send_notable_event_to_fireeye_helix STDERR - File "/opt/splunk/etc/apps/TA-fireeye-helix-api-integration/bin/ta_fireeye_helix_api_integration/logging_helper.py", line 1, in <module>
08-23-2021 16:59:12.016 +0000 ERROR sendmodalert [19189 AlertNotifierWorker-0] -

**Comment by stboch** [comment]
I am not sure anyone at FireEye maintains this app anymore. Also I didn't even know there was an alert action for this app. it looks like your app is a different more custom app.
